### ISSUE TITLE
v.75 not accepting weekly quests - need a way to be able to

### ISSUE THREAD

**Issue by hollo6** [p3lim-wow/QuickQuest#103]
**Describe the bug**
As described in https://github.com/p3lim-wow/QuickQuest/issues/101, weekly quests are now no longer automatically accepted on alts, which for me, and I guess a lot of people, makes the whole feature essentially useless since we're kind of only doing weeklies now.

**How to reproduce**
Talk to an NPC that gives a weekly quest (crafting, worldsoul, weekend event, etc.).

**What did you expect?**
There should be an option to still accept weekly quests if they were accepted/completed on another character.

**Screenshots**
N/A

**Comment by p3lim** [comment]
https://github.com/p3lim-wow/QuickQuest/commit/1ee376b903d6e3c5735632cb4c290354c539daa6
