### ISSUE TITLE
You are not high enough for that quest

### ISSUE THREAD

**Issue by Thijs-Velde** [p3lim-wow/QuickQuest#15]
"You are not high enough for that quest" keeps popping up while I have Glittering Star Chart in my bags, an item from the new class order hall from mages.

**Comment by p3lim** [comment]
Blizzard forgot to add information to the tooltip about item requirement on that item.  
As a temporary solution I'd ask you to add it to the item filter, but that feature doesn't work properly on the beta right now.

**Comment by p3lim** [comment]
This should have been resolved on the beta from my testing, feel free to let me know if it still occurs.
