### ISSUE TITLE
Error at login

### ISSUE THREAD

**Issue by daneras** [p3lim-wow/QuickQuest#16]
Hi p3lim,

i downloaded your files from here today an installed it on Beta. Got the following error message at login with the char:

> 
> Message: Interface\AddOns\QuickQuest\Config.lua:12: Cannot find a library instance of "Wasabi".
> Time: Tue Jul 19 12:39:48 2016
> Count: 1
> Stack: [C]: in function `error'
> Interface\AddOns\HandyNotes\Libs\LibStub\LibStub.lua:23: in function `LibStub'
> Interface\AddOns\QuickQuest\Config.lua:12: in main chunk
> 
> Locals: (*temporary) = "Cannot find a library instance of "Wasabi"."

The old release version works fine. 60100.20

**Comment by p3lim** [comment]
That's because the repository here does not come with the necessary libraries, they are automatically packaged when I release new versions.

**Comment by daneras** [comment]
Ok, many thx, i just use the old one for now.

**Comment by phant** [comment]
get same problem with 70000.23

**Comment by p3lim** [comment]
> get same problem with 70000.23

@phant On the version from curse/wowi?
