### ISSUE TITLE
Blacklist will be ignored completely after Update for legion!

### ISSUE THREAD

**Issue by q3fuba** [p3lim-wow/QuickQuest#19]
Hi,
Since the update for legion the blacklist will be ignored completely.
Also some Icons are not visible when open the Blacklist and this is NOT just at the first login as reported by some other users.

Tested the Blacklist with all Garrison "Scouting Missive" and all "Darkmoon Quest" Items.
Every item will be accepted instantly but there are ALL on the Blackist.

**Comment by p3lim** [comment]
Blizzard added their own auto-starting thing to the game which I can't disable, it is _not_ QuickQuest doing it.

**Comment by q3fuba** [comment]
ah damn...
I dont know this, sorry then :/
