### ISSUE TITLE
Request: Auto Accept Nomi from Cooking School Bell 

### ISSUE THREAD

**Issue by Thijs-ter-Velde** [p3lim-wow/QuickQuest#20]
Nomi, summoned from the Cooking School Bell, has a daily level 90 quest. In WoD QuickQuest would accept and complete this quest, but in Legion the quest became trivial due to being low level. This makes the addon ignore the quest, leading to the inevitable, first world, issue of having to manually click the quest to accept it myself. (Totally unacceptable of course).

I would like an exception in Quick Quest to still accept Nomis quest despite being trivial, or, an option to always accept a quest, trivial or not.

**Comment by p3lim** [comment]
Enable tracking of low level quests on your minimap, QuickQuest is governed by this option.
