### ISSUE TITLE
QuickQuest-70000.23-Release.lua:124: attempt to call global 'GetActiveGossipQuestInfo' (a nil value)

### ISSUE THREAD

**Issue by Starfox** [p3lim-wow/QuickQuest#22]
If you're opening a feature request, please search through the existing issues first.  
If you're submitting an issue, please fill in the following:
- What version are you using?

70000.23-Release
- Can the issue be reproduced, and if so, how?
- If there was an error message, please include it.

```
16x QuickQuest\QuickQuest-70000.23-Release.lua:124: attempt to call global 'GetActiveGossipQuestInfo' (a nil value)
QuickQuest\QuickQuest-70000.23-Release.lua:124: in function <QuickQuest\QuickQuest.lua:115>
QuickQuest\QuickQuest-70000.23-Release.lua:20: in function `?'
QuickQuest\QuickQuest-70000.23-Release.lua:2: in function <QuickQuest\QuickQuest.lua:2>

Locals:
npcID = 93603
active = 3
(for index) = 1
(for limit) = 3
(for step) = 1
index = 1
(*temporary) = nil
(*temporary) = 1
(*temporary) = "attempt to call global 'GetActiveGossipQuestInfo' (a nil value)"
GetNPCID = <function> defined @QuickQuest\QuickQuest.lua:34
ignoreQuestNPC = <table> {
 111243 = true
 88570 = true
 87391 = true
}
IsTrackingHidden = <function> defined @QuickQuest\QuickQuest.lua:38
rogueClassHallInsignia = <table> {
 93188 = true
 97004 = true
 96782 = true
}
ignoreGossipNPC = <table> {
 86927 = true
 95144 = true
 95146 = true
 86933 = true
 86945 = true
 84684 = true
 95139 = true
 95141 = true
 95143 = true
 86682 = true
 79740 = true
 86934 = true
 84511 = true
 84268 = true
 79953 = true
 86946 = true
 95201 = true
 95142 = true
 95145 = true
 95200 = true
 86964 = true
}
```
- If there is a graphical issue, please include a screenshot (you can drag-n-drop here).

Make sure you check back often until the issue is resolved for any follow-up questions.

**Comment by p3lim** [comment]
You're missing libraries, where did you get this version?

**Comment by Starfox** [comment]
Curse client, no lib version, guess that does not get resolved right?

**Comment by Starfox** [comment]
A library also should have an API and not just leak it into global

**Comment by p3lim** [comment]
Did you download that with or without the curse client?

**Comment by p3lim** [comment]
Did you set QuickQuest to install libraries separately or did you explicitly get the nolib version?

**Comment by Starfox** [comment]
7.1.6107.43498 beta

i have all my addons set to download libs seperately

**Comment by p3lim** [comment]
No longer allowing packaging nolib versions, should resolve this.
