### ISSUE TITLE
Some issue with popup quests

### ISSUE THREAD

**Issue by p3lim** [p3lim-wow/QuickQuest#23]
https://mods.curse.com/addons/WoW/quickquest?comment=65

> BUG - the bug still persists that any quest that auto pops up for the player that they did not explicitly click an NPC to view (legion pre-quest, etc) causes strange behavior to the game. I thought this was relating to talking head quests specifically (mentioned by another user below), however, noticed this same issue in zones such as Throne of Thunder when entering an area which would normally pop a zone quest (ie- walking over/near the giant exclamation mark).
> 
> Behavior is as follows:
> The quest window never pops up (it seems to be blocked by the addon). Following this, any attempts to use NPC dialogs (gossip, bank, merchants, even class order hall/garrisons) will now automatically close about 1-5 seconds after opening (presumably because the quest window is trying to open again, but never shows because it is still being blocked by the addon). Reloading does not fix this. Only by disabling QuickQuest and reloading will this issue resolve.
> 
> An example:
> Did an old content run to ToT, walked over a floating exclamation, no quest popup. Didn't notice until I had ported back to my class order hall following completion of raid and tried using my order hall table. Window continuously closes automatically. I am able to identify this bug easily when it happens (repeatable), so I disabled the addon, and immediately was prompted to accept the ToT quest that didn't popup before.
> 
> Please fix this. This bug doesn't prevent me from using the addon but took me forever to diagnose which could be frustrating to some users.

**Comment by p3lim** [comment]
Can't replicate.

**Comment by Tabrarian** [comment]
This issue has occurred for me with auto-quests in the world and also quests from the Adventure Guide. Most recently, the Halls of Reflection auto-quest caused the behaviour. I think, however, that it specifically occurs when the user selects the option to "reverse the behaviour of the modifier key". In testing recently, I observed the following results:

- With the reverse modifier option unselected:
-- I was able to accept quests from the Adventure Guide.
-- The Legion intro auto-quests work correctly.
- With the reverse modifier option selected:
-- I couldn't accept quests from the Adventure Guide. Holding the modifier key doesn't affect the result.
-- Auto-quests don't initiate properly.

I don't know if this is really fixable, but thought it could help to shed some light on the issue for other users.

**Comment by siweia** [comment]
It initially occurred in Legion pre-patch, since quickquest got a big update that removed those "atMail atBank" functions. While old version of quickquest was doing totally fine back then.
So I have to stay on the old version and combine it with new blacklist and world quest filter for personal use till now.
