### ISSUE TITLE
QuickQuest 70100.27: LUA Error at login

### ISSUE THREAD

**Issue by daneras** [p3lim-wow/QuickQuest#24]
Hi P3lim,

i get an error at every login or reload from the UI. Only other Addon is nMainbar. Cleared the Cache and deleted the WTF for testing.

**Errormessage:**

> Message: Interface\AddOns\QuickQuest\QuickQuest.lua:19: attempt to index global 'QuickQuestDB' (a nil value)
> Time: Wed Nov 30 15:42:49 2016
> Count: 1
> Stack: Interface\AddOns\QuickQuest\QuickQuest.lua:19: in function `?'
> Interface\AddOns\QuickQuest\QuickQuest.lua:2: in function <Interface\AddOns\QuickQuest\QuickQuest.lua:2>
> 
> Locals: (*temporary) = nil
> (*temporary) = nil
> (*temporary) = "attempt to index global 'QuickQuestDB' (a nil value)"
> modifier = false
> DISABLED = nil
> method = <function> defined @Interface\AddOns\QuickQuest\QuickQuest.lua:237

Greetings,
Daneras

**Comment by p3lim** [comment]
https://github.com/p3lim-wow/QuickQuest/commit/4838c511093e7038c5336595d5c3e2f8a5bde611
