### ISSUE TITLE
Ignore Proving Grounds gossip by looking for that string instead of npc blacklist

### ISSUE THREAD

**Issue by Stanzilla** [p3lim-wow/QuickQuest#26]
15:29:16  p3lim: What is the string (exactly)?
15:30:11  Stanzilla: Enter the Proving Grounds
15:30:24  Stanzilla: 105991 is the npc id
15:30:33  p3lim: nothing for that, closes is "Proving Grounds" or "Proving Grounds:"
15:31:06  Stanzilla: I don't think there is any other gossip option that includes "proving grounds" so can probably use that for matching?
15:31:15  p3lim: I could

**Comment by EKE00372** [comment]
and Nexus-Lord Donjon Rade Sr?
it's a NPC for portal to dungeon/raid zone.

ps. have complete zhTW/zhCN on curse.

**Comment by p3lim** [comment]
@EKE00372 I don't filter placeholder NPCs for the PTR.

**Comment by p3lim** [comment]
https://github.com/p3lim-wow/QuickQuest/commit/f6dc7ebdd2e9d5b4fb8987291159c7fa8b11dcb2
