### ISSUE TITLE
Add "High Exarch Turalyon" ignore.

### ISSUE THREAD

**Issue by Wetxius** [p3lim-wow/QuickQuest#27]
Hello.
Can you add High Exarch Turalyon for ignore npc? He gives weekly quest that use Order Resources.
	[124312] = true,	-- High Exarch Turalyon (he will eat your resources)
	[126954] = true,	-- High Exarch Turalyon (he will eat your resources)

**Comment by Kalteew** [comment]
Hi.

Or you could simply add the quest "Fueling the antoran Campaign" (48636)
And if you do so, can you add "Further Supplying Krokuun" (48634) and "More Void Inoculation" (48635)
Thank you
