### ISSUE TITLE
Legion first aid quests and items ids

### ISSUE THREAD

**Issue by warkol66** [p3lim-wow/QuickQuest#29]
Hi, in case someone wants to add legion first aid quests to the ignore list

		-- First Aid
		[42350] = 139534, -- Bloody Letter
		[42255] = 139522, -- Bloody Note
		[42308] = 139527, -- Bloody Plea
		[42351] = 139535, -- Bloody Prayer
		[42309] = 139528, -- Bloody Request
		[42333] = 139524, -- Crumpled Letter
		[42334] = 139525, -- Crumpled Note
		[42058] = 139531, -- Crumpled Request
		[42323] = 139523, -- Fevered Letter
		[42303] = 139526, -- Fevered Note
		[42250] = 139520, -- Fevered Plea
		[42345] = 139532, -- Fevered Prayer
		[41985] = 139529, -- Fevered Request
		[42215] = 139530, -- Singed Letter
		[42245] = 139521, -- Singed Note
		[42340] = 139533, -- Singed Plea

Great addon!!

**Comment by p3lim** [comment]
I'm assuming that the general user _wants_ to do those quests, and others can blacklist them through the config in-game (`/quickquest`).

**Comment by warkol66** [comment]
Well, that's arguable, if you already did all the quests for the achievement and you are 800 in first aid, there is no point to repeat the quests.
The problem it's that if you already have quickquest, you will never see the item to add to the ignore list via the interface.
Just posted the list to save some time looking for the items and quests ids

**Comment by p3lim** [comment]
Fair point.

**Comment by warkol66** [comment]
Hi again, unfortunately adding first aid quest items to the personal blacklist didn't work.

Edited SavedVariables\QuickQuest.lua added the items, open WOW and confirmed items are in blacklist via /qq, but today I looted one of those items and the quest was "auto-accepted". 

Maybe there is no way to no block auto-accept this kind of quest....
Anyway, thanks for the addon

**Comment by p3lim** [comment]
QuickQuest does not auto-start quests from items, the game itself does that.

**Comment by warkol66** [comment]
Yeap, I know, maybe my English it's not good enough to express my self.

I'm not blaming QuickQuest for this, just tried to figure out how to block legion First Aid quest to be accepted at all. Rewards is ridicules, doesn't count to dailies, etc. (I'm blaming blizzard for this lol )

I was trying to emulate the behavior of other items such as Darkmoon fair, etc, but since the item doesn't stay in inventory, seems not to be able to be blocked by QQ blacklist, that's it ... 

Really don't know why, so thought could be useful to post the info for someone with more knowledge of addons, wow client etc. 

Hope didn't distracted much 
Thx

**Comment by p3lim** [comment]
BfA removed First Aid.
