### ISSUE TITLE
Lua Error on login

### ISSUE THREAD

**Issue by Galiwyx** [p3lim-wow/QuickQuest#30]
Hello,

Since the release of 8.0.1 I have an error : 

`Message: Error loading Interface\AddOns\QuickQuest\libs\Wasabi\LibStub\LibStub.lua
Time: Wed Jul 18 13:15:07 2018
Count: 3`

Thank you :)

**Comment by p3lim** [comment]
https://github.com/p3lim-wow/QuickQuest/commit/7399418caba46822bf06ea99ec8ed6e397b1d456
