### ISSUE TITLE
about sharing quest.

### ISSUE THREAD

**Issue by yishuangfrank** [p3lim-wow/QuickQuest#34]
When I accept a new quest, QuickQuest always shares it to my groupmates.

Could you close this feature or add an on/off option, please?

**Comment by p3lim** [comment]
That is an option which is turned **off** by default, you must have turned it on.
Open up the config window to turn it off again.

**Comment by yishuangfrank** [comment]
Thanks，I will check it later.

**Comment by yishuangfrank** [comment]
Could you help me to find the option please？

**Comment by p3lim** [comment]
It's literally the top one.
