### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by yishuangfrank** [p3lim-wow/QuickQuest#37]
I love this addon!

I was wondering if you can add a blacklist for NPC?

**Comment by p3lim** [comment]
See #11, but I don't really play the game any more. If someone submits a patch for it I'd be more than happy to add it in.

**Comment by yishuangfrank** [comment]
Someone took over "Quest-o-matic" and added the blacklist for NPC. 

However, we need to change "Core.lua" by ourself, using the following macro to get the target NPC's ID:
/run a=UnitGUID("target") if a==tonumber(string.match(UnitGUID('target'),'')) then end print(a)

[Questomatic 2019.4.11.zip](https://github.com/p3lim-wow/QuickQuest/files/3409867/Questomatic.2019.4.11.zip)

**Comment by p3lim** [comment]
You can do the same in QuickQuest https://github.com/p3lim-wow/QuickQuest/blob/master/QuickQuest.lua#L47

**Comment by yishuangfrank** [comment]
Thanks！

**Comment by p3lim** [comment]
Implemented in https://github.com/p3lim-wow/QuickQuest/commit/a9c44249c2d52b448482ff78f4ffc865c4faf0d9.
