### ISSUE TITLE
Unable to open quest log on some characters

### ISSUE THREAD

**Issue by jrowles** [p3lim-wow/QuickQuest#45]
**Describe the bug**
When this addon is enabled, some of my characters are unable to open the quest log.  No lua error is displayed, the small world map/quest log just doesn't open.  The full size map still continues to open.

**How to reproduce**
Enable addon, try to open quest log.

**What did you expect?**
The quest log to appear.

**Screenshots**
My quests:

![image](https://user-images.githubusercontent.com/14367258/97844980-f206ee00-1cb9-11eb-8847-77979f622632.png)

**Comment by p3lim** [comment]
Please try out this version:
https://github.com/p3lim-wow/QuickQuest/suites/1464410901/artifacts/25110096

You have to be logged in to GitHub to get the download.

**Comment by jrowles** [comment]
@p3lim No dice.

**Comment by jrowles** [comment]
@p3lim What did you actually change?  Doing a diff and the only files I see changed (compared to latest release) are

- SavedVariables.lua
- CHANGELOG.md
- QuickQuest.toc

**Comment by p3lim** [comment]
I pushed a release shortly after, just to fix another bug (the chat spam when opening the interface options).

Can you get me a copy of your taint.log file _after_ you've encountered this bug on a character and logged completely out? Please use gist.github.com or some pastebin instead of dumping all of the contents of that file here.

**Comment by jrowles** [comment]
@p3lim There is no taint logged.  I enabled the cvar, but no taint.log file is created when reproducing this issue.

**Comment by p3lim** [comment]
Can you revert to 90000.43-Release and see if the issue is there? I have a hunch.
You'll need to delete the savedvariables first if doing so (`WTF/Account/<your account id>/SavedVariables/QuickQuest.lua`).

**Comment by jrowles** [comment]
@p3lim The issue is ShowQuestOffer(questID).  Commenting out this line fixes the issue.  I also added a print and it is failing on questId 57249.

**Comment by p3lim** [comment]
90000.48-Release is pushed, should be out momentarily.

**Comment by jrowles** [comment]
@p3lim Huzzah, thank you for the turnaround!

**Comment by p3lim** [comment]
Thank you for being patient and very helpful in finding the cause, this one had me stumped!
