### ISSUE TITLE
addon not working as intented

### ISSUE THREAD

**Issue by matton300** [p3lim-wow/QuickQuest#59]
**Describe the bug**
trying to quick quest a npc with 2 quests and it does nothing

getting this error

10x Interface/AddOns/QuickQuest/Utils.lua:71: attempt to call global 'GetNumTrackingTypes' (a nil value)
[string "@Interface/AddOns/QuickQuest/Utils.lua"]:71: in function `ShouldAcceptTrivialQuests'
[string "@Interface/AddOns/QuickQuest/Addon.lua"]:144: in function `func'
[string "@Interface/AddOns/QuickQuest/Utils.lua"]:52: in function `Trigger'
[string "@Interface/AddOns/QuickQuest/Utils.lua"]:6: in function <Interface/AddOns/QuickQuest/Utils.lua:5>

Locals:
(*temporary) = 1
(*temporary) = nil
(*temporary) = "attempt to call global 'GetNumTrackingTypes' (a nil value)"

another

2x Interface/AddOns/QuickQuest/config/Options.lua:83: attempt to index global 'InterfaceOptionsFrameAddOns' (a nil value)
[string "@Interface/AddOns/QuickQuest/config/Options.lua"]:83: in main chunk

Locals:
addonName = "QuickQuest"
ns = <table> {
 CreateButtonPool = <function> defined @Interface/AddOns/QuickQuest/config/ButtonPoolMixin.lua:133
 L = <table> {
 }
 GetNPCID = <function> defined @Interface/AddOns/QuickQuest/Utils.lua:63
 ShouldAcceptTrivialQuests = <function> defined @Interface/AddOns/QuickQuest/Utils.lua:70
 EventHandler = Frame {
 }
 tLength = <function> defined @Interface/AddOns/QuickQuest/Utils.lua:79
}
L = <table> {
}
CreateOptions = <function> defined @Interface/AddOns/QuickQuest/config/Options.lua:4
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'InterfaceOptionsFrameAddOns' (a nil value)"

**Comment by matton300** [comment]
hi, when i have 2 quests to turn in, the addon doesn't auto complete it

**Comment by p3lim** [comment]
Which quests?

**Comment by matton300** [comment]
https://www.wowhead.com/quest=14107/the-fate-of-the-fallen
https://www.wowhead.com/quest=14108/get-kraken

these are some quests by [Crusader Silverdawn](https://www.wowhead.com/npc=35094/crusader-silverdawn)

they are blue quest and the other less light blue

**Comment by p3lim** [comment]
I'll assume you're level 60. Those are trivial quests, you'll need to track trivial quests to accept/complete them. I might change this logic to only prevent picking up trivial quests but allow delivery.
