### ISSUE TITLE
Add Shadowland Revendreth items to exceptions

### ISSUE THREAD

**Issue by warkol66** [p3lim-wow/QuickQuest#62]
Hi, just suggest to add the items that are turned to Ta'xera for anima vessels to auto accept exceptions.
I visit Revendreth for treasurers and the 35 anima vessel is not worth the travel to the black market site
Ids=173705,173707,173709,173710,173711,173712,173715,173717,173718,173719,173720,173721,180453
Link to objects in wowhead
https://www.wowhead.com/item=173705/the-venthyr-diaries
https://www.wowhead.com/item=173707/soul-hunters-blade
https://www.wowhead.com/item=173709/vial-of-dredger-muck
https://www.wowhead.com/item=173710/petrified-stonefiend
https://www.wowhead.com/item=173711/portrait-of-the-sire
https://www.wowhead.com/item=173712/ledger-of-souls
https://www.wowhead.com/item=173715/dredgers-toolkit
https://www.wowhead.com/item=173717/perfected-hand-mirror
https://www.wowhead.com/item=173718/bottle-of-redelav-wine
https://www.wowhead.com/item=173719/pristine-dredbat-fang
https://www.wowhead.com/item=173720/glittering-primrose-necklace
https://www.wowhead.com/item=173721/love-and-terror
https://www.wowhead.com/item=180453/she-had-a-stone-heart

**Comment by p3lim** [comment]
QuickQuest does not handle items that starts quests, that's Blizzard's doing.

**Comment by warkol66** [comment]
No? are you sure? 
What about darkmoon's items? or BoA?. It's not the first time I contribute with comments on this issue.
There is also a whole section in the in-game settings regarding Items.
If this anima stuff items are different, the answer is there are different and QQ can't manage these exceptions

**Comment by p3lim** [comment]
There's nothing in QuickQuest that uses items that starts quests from the bags, Blizzard started doing in with the start of Legion. Here's the commit where I removed all the code in QuickQuest for it 6 years ago: https://github.com/p3lim-wow/QuickQuest/commit/76cccb4165cb5c37b2f1dafecb78c7b98dd6b9db

**Comment by warkol66** [comment]
It's not from the inventory, is on loot.
I'm still looting Darkmoon items (like Captured Insignia or Mysterious Grimoire) and quest are not prompted, neither auto accepted.
I appreciate your effort for maintaining the add-on, don't want to argue since you must know the add on more than anyone, but maybe we are referring to different issues.
The quest items I'm referring to are loot from chests or rares, and auto accepted. It not a matter of life and death, just trying to add my two cents

**Comment by p3lim** [comment]
Regardless of when, QuickQuest never starts quest items, Blizzard does. Locking this issue now.
