### ISSUE TITLE
Issue with addon not continuously turning in items for quests

### ISSUE THREAD

**Issue by Fernski** [p3lim-wow/QuickQuest#65]
Issue with addon not continuously turning in items for quest it was working fine but then all the sudden I have to keep clicking npc for it to turn items but before it would just keep turning items in since it’s a renown quest.

**Comment by p3lim** [comment]
Assuming this is about quests that turn in tokens for reputation. This has always been the case, as it depends on the order of events occurring, QuickQuest doesn't continously check it just reacts to events. If a _new_ quest appears, e.g. you've turned in bunches of 5 tokens, then you only have multiples of 1 tokens left, it tends to get stuck.

**Comment by p3lim** [comment]
As a good example of this is the Vault Artifacts repeatable delivery. There are two types of quest NPCs; those who use the gossip API (e.g. they typically have other dialog options other than only quests) and those who only use the quest API. The gossip NPCs usually return you to the main gossip page after delivering a quest, while the ones using the quest API don't. The Vault Artifacts NPC uses the quest API, and the only way QuickQuest can deliver more than one quest to this NPC is if there are multiple _different_ quests available to deliver. If there is only one quest the NPC closes the dialog after you deliver the quest and there is no way to continue delivering without the player manually talks to the NPC again. There is no way around this limitation.

@Fernski Please let me know if this accurately describes your issue.

**Comment by Fernski** [comment]
P3lim yes this is a perfect description. Thank you
