### ISSUE TITLE
NPC blocklist not being considered

### ISSUE THREAD

**Issue by hollo6** [p3lim-wow/QuickQuest#67]
**Describe the bug**
As of version 100007.60-Release, NPC blocklist has no effect.
I have an NPC in the list, it says so when I try to re-add it ("already blocked"), and it still turned in my artifacts automatically :(
Would be even better if the reputation turn-in quests were not auto-complete by default.

**How to reproduce**
1. Add an NPC to blocklist, e.g. Cataloger Jakes
2. Interact with NPC while having any active completed quests with that NPC
3. Observe the quest will be turned in despite the NPC being on the blocklist

**What did you expect?**
No quests should be automatically turned in with blocklisted NPCs.

**Comment by hollo6** [comment]
Or better yet, an option to not turn in any repeatable quests like AutoTurnIn has, would be the best solution.

**Comment by p3lim** [comment]
How about both? :)
