### ISSUE TITLE
Bag update - wotlk error

### ISSUE THREAD

**Issue by SpeedySaky** [p3lim-wow/QuickQuest#68]
Message: Interface/AddOns/QuickQuest/QuickQuest.lua:316: attempt to call global 'GetContainerNumSlots' (a nil value)
Time: Tue Apr  4 11:05:34 2023
Count: 27
Stack: Interface/AddOns/QuickQuest/QuickQuest.lua:316: attempt to call global 'GetContainerNumSlots' (a nil value)
[string "=[tsm error check]"]:1: in main chunk
[string "=(tail call)"]: ?
[string "=[C]"]: in function `GetContainerNumSlots'
[string "@Interface/AddOns/QuickQuest/QuickQuest.lua"]:316: in function <Interface/AddOns/QuickQuest/QuickQuest.lua:312>
[string "@Interface/AddOns/QuickQuest/QuickQuest.lua"]:57: in function `?'
[string "@Interface/AddOns/QuickQuest/QuickQuest.lua"]:2: in function <Interface/AddOns/QuickQuest/QuickQuest.lua:2>

Locals:

**Comment by p3lim** [comment]
Only retail is supported.
