### ISSUE TITLE
10.1 all options reset and can't be changed

### ISSUE THREAD

**Issue by hollo6** [p3lim-wow/QuickQuest#72]
**Describe the bug**
Since 10.1, all options were reset and unticking them is possible but it won't stick and all of them will be reset to default, leading to a lot of grief :( Accidental automatic quest item selection for example.

**How to reproduce**
1. Uncheck any option.
2. Reload.
3. Observe that all options are checked again.

**What did you expect?**
Changed (disabled) options should retain their new state.

**Comment by hollo6** [comment]
No.
Reverted to 100007.62-Release, this still seems to work.

**Comment by Snaflus** [comment]
I want to add that the setting doesn't just reset, it doesn't change any functionality. For example if I change "Reverse the behaviour of the modifier key" no addon behavour changes even though the setting keeps its state through closing and opening the menu. Tested without any other addons enabled. Also settings reset to default after reload for me too.

**Comment by hollo6** [comment]
Yeah I might worded it poorly.
Doesn't matter if I enable/disable any of the default settings, it will still behave like the default and the state of the checkbox will revert after reload.
