### ISSUE TITLE
Please make available for Classic WOTLK

### ISSUE THREAD

**Issue by realrobd** [p3lim-wow/QuickQuest#76]
Please make available for Classic WOTLK <3

**Comment by p3lim** [comment]
There are better alternatives (Questie, Leatrix), and I can't to support something I can't maintain (I don't play classic, nor will I).

**Comment by realrobd** [comment]
> There are better alternatives (Questie, Leatrix), and I can't support something I can't maintain (I don't play classic).

Meh, yours has a couple features they do not.
Oh well, thanks for the reply :)
