### ISSUE TITLE
addon stopped working on it's own

### ISSUE THREAD

**Issue by clawme** [p3lim-wow/QuickQuest#77]
addon was doing it's thing just fine for a daily repeatable quest but when I left to get more of the turn in it suddenly no longer works. Deleting and reinstalling didn't change anything as well so now it only accepts, turns in, and completes once after I have to interact with the npc each time. Only thing that changed was me leaving to buy more fish

**Comment by p3lim** [comment]
NPCs work on one of two systems; Quest (NPC only offer quests) and Gossip (NPC offers quests and optionally has other dialogue). The latter will exit their interaction with the player after finishing all quests they offer and there are no more dialogue options. Which system an NPC uses is sometimes quite random.

This is something that QuickQuest has no control over, so my suggestion is to try to always have one interaction remaining with an NPC if you want to deliver a lot of repeatables, or alternatively bind an interaction key that you can spam click.
