### ISSUE TITLE
Removed NPC showing as background in the NPC block list, in the slot of a newly added NPC.

### ISSUE THREAD

**Issue by cgsub** [p3lim-wow/QuickQuest#83]
**Describe the bug**
In the NPC block list the image of a removed NPC is showing as background to a newly added NPC.

**How to reproduce**
I Added an NPC (Xuen) to the block list.  
It was the Xuen south of the Temple of the White Tiger (in Peak Of Serenity)  ID: 60968
Then I added a few other NPC in between. 
I then removed Xuen.
I added another NPC :  Elder Anli <Serpent Master> ID: 58564

**What did you expect?**
To only see the image of Elder Anli <Serpent Master> in the list instead of both Xuen and her in the same slot. 
Note that moving the mouse pointer over the slot only shows Elder Anli as expected.

**Screenshots**
![image](https://github.com/p3lim-wow/QuickQuest/assets/72781235/ce05b00b-bff9-4ffb-af03-2257f199f9c3)

**Comment by p3lim** [comment]
Currently working on some stuff before TWW launches so this fix won't be released for a while, but thanks for reporting!
