### ISSUE TITLE
11.0 Quest completion text omitted

### ISSUE THREAD

**Issue by hollo6** [p3lim-wow/QuickQuest#86]
**Describe the bug**
In 11.0, the "<quest name> completed." messages are missing from the chat for most (but nut all) quests.
Examples of missing ones: emissary/paragon quests, daily quests and also some regular quests I sadly can't remember the name of.
Not missing: Show Your Mettle, some regular quests.

**How to reproduce**
Complete any quests with autocomplete enabled.

**What did you expect?**
Quest completion text in chat.

**Screenshots**
N/A

**Comment by p3lim** [comment]
Don't think QuickQuest could contribute to this, have you tested to make sure it also happens with QuickQuest disabled?

**Comment by hollo6** [comment]
Not happening anymore. Guess it was just one of the 98438625 prepatch bugs. Sorry.
