### ISSUE TITLE
Translation:zhCN.lua

### ISSUE THREAD

**Issue by yizhiyang2011** [p3lim-wow/QuickQuest#88]
local L = select(2, ...).L('zhCN')

L['Automatically accept quests'] = '自动接受任务'
L['Automatically complete quests'] = '自动完成任务'
L['Automate repeatable quests'] = '自动完成可重复任务'
L['Highlight valuable reward'] = '自动选最贵的奖励'
L['Automatically share quests'] = '自动分享任务'
L['Skip quest gossip options'] = '自动跳过任务对话'
L['Automate gossip options'] = '自动对话选择任务'
L['When to automate gossip'] = '什么时候启用自动任务'
L['Never'] = '从不'
L['Soloing'] = '单人'
L['Always'] = '总是'
L['Pay Darkmoon Faire teleport'] = '自动支付暗月马戏团传送费'
L['Pause mode modifier'] = '暂停自动任务按键'
L['Hold this key to temporarily disable all automation'] = '按住此键暂时禁用自动执行'
L['Reverse pause mode'] = '反转暂停自动任务按键'
L["While the pause key is NOT held don't automate anything"] = '在没有按住暂停键的情况下禁用自动执行'
L['Block a new item by ID'] = '阻止新物品标题或者编号'
L['Block a new NPC by ID or target'] = '阻止新NPC编号或者当前目标'
L['Block a quest by title or ID'] = '阻止新任务标题或者编号'
L['Item Blocklist'] = '阻止物品名单'
L['NPC Blocklist'] = '阻止NPC名单'
L['Quest Blocklist'] = '阻止任务名单'
L['ALT key'] = 'Ctrl键'
L['CTRL key'] = 'Shift键'
L['SHIFT key'] = 'Alt键'

**Comment by p3lim** [comment]
You will need to provide some actual translations :smiley: 
Please use the template.

**Comment by yizhiyang2011** [comment]
local L = select(2, ...).L('zhCN')

L['Automatically accept quests'] = '自动接受任务'
L['Automatically complete quests'] = '自动完成任务'
L['Automate repeatable quests'] = '自动完成可重复任务'
L['Highlight valuable reward'] = '自动选最贵的奖励'
L['Automatically share quests'] = '自动分享任务'
--L['Skip quest gossip options'] = '自动跳过对话'
--L['Automate gossip options'] = '自动对话选择任务'
L['When to automate gossip'] = '什么时候启用自动任务'
L['Never'] = '从不'
L['Soloing'] = '单人'
L['Always'] = '总是'
L['Pay Darkmoon Faire teleport'] = '自动支付暗月马戏团传送费'
L['Pause mode modifier'] = '停用自动任务按键'
L['Hold this key to temporarily disable all automation'] = '按住此键暂时禁用自动执行'
L['Reverse pause mode'] = '反转停用自动任务按键'
L["While the pause key is NOT held don't automate anything"] = ''
L['Block a new item by ID'] = '阻止物品名单'
L['Block a new NPC by ID or target'] = '阻止NPC名单'
L['Block a quest by title or ID'] = '阻止任务名单'
L['Item Blocklist'] = '阻止物品名单'
L['NPC Blocklist'] = '阻止NPC名单'
L['Quest Blocklist'] = '阻止任务名单'
L['ALT key'] = 'Ctrl键'
L['CTRL key'] = 'Shift键'
L['SHIFT key'] = 'Alt键'

**Comment by yizhiyang2011** [comment]
![QuickQuest1](https://github.com/user-attachments/assets/c4b08574-5ed7-4da2-a95e-d803b4100c9b)

**Comment by p3lim** [comment]
You just forgot to uncomment two strings, that's fine.

There's one string you missed, the tooltip for "Reverse pause mode":

```lua
L["While the pause key is NOT held don't automate anything"] = ""
```

**Comment by p3lim** [comment]
These three lines should be improved;
```lua
L['Block a new item by ID'] = '阻止物品名单'
L['Block a new NPC by ID or target'] = '阻止NPC名单'
L['Block a quest by title or ID'] = '阻止任务名单'
```
They're used in the popup when you press the "Add" button in the blocklist options.

**Comment by p3lim** [comment]
https://github.com/p3lim-wow/QuickQuest/commit/4f5aea4b8566e8cd962cbb0c761527852cbba935
