### ISSUE TITLE
11.0.2 modified-key quick quest failed.

### ISSUE THREAD

**Issue by xanahopper** [p3lim-wow/QuickQuest#90]
**Describe the bug**

As described, failed. reported an error on buggrubber.

**How to reproduce**

**What did you expect?**

**Screenshots**

![image](https://github.com/user-attachments/assets/3aa03a69-df85-43d8-8733-6eef09ec652c)

**Comment by p3lim** [comment]
https://github.com/p3lim-wow/Dashi/commit/5e046071edbe745ee4b67699e125684e1371b7ef
