### ISSUE TITLE
Automation is stuck with QuestFrame hidden

### ISSUE THREAD

**Issue by Pingumania** [p3lim-wow/QuickQuest#92]
**Describe the bug**
If a quest is turned in and a new quest becomes available, the QuestFrame often remains hidden and can't be interacted with anymore.
The new quest also isn't accepted.

**How to reproduce**
It doesn't always happen, but it usually happens if you turn in a quest and another becomes available after.

**Workaround**
You have to move away from the npc until you hear the QuestFrame closing (even if it is hidden) then talk to npc again.

**Comment by p3lim** [comment]
I've noticed this too, kinda hard to reproduce consistently, but I'm looking into it.

**Comment by Pingumania** [comment]
Let me know if you need someone to test something, I get this almost every time. Might be because the zones are kinda laggy right now (at least on EU).

**Comment by p3lim** [comment]
Can't reproduce this any more, guess it was just lag during the launch.
