### ISSUE TITLE
Weekly Spider Pact Quest UI Keeps Popping Up in Azj-Kahet

### ISSUE THREAD

**Issue by Soeroah** [p3lim-wow/QuickQuest#98]
**Describe the bug**
After my alts pick up the spider pact weekly quest, the UI showing the quest and its rewards continuously pops up as I fly through the zone, interrupting my gameplay.

**How to reproduce**

**What did you expect?**

**Screenshots**
![1](https://github.com/user-attachments/assets/0568225b-36ed-465e-bf0f-f1f76f74e5ed)

**Comment by p3lim** [comment]
Is this quest started from an item?

**Comment by Soeroah** [comment]
No, it's a quest you pick up from the renown vendor in the weaver's base

Despite being picked up from an NPC, something is throwing that quest 'accept' prompt up every time I check my zone map

I'm not entirely sure it's this addon though, I think I posted to the wrong one
