### ISSUE TITLE
[New] Marker in the addon options doesn't go away

### ISSUE THREAD

**Issue by Adrenalined** [p3lim-wow/QuickQuest#99]
**Describe the bug**
There is a "New" marker for options in the addon options screen.  This "New" tag doesn't go away.

**How to reproduce**
Open addon options after installing the addon

**What did you expect?**
Once the "New" option is viewed, it won't continuously show.

**Screenshots**
https://imgur.com/a/ncUwSlt

**Comment by Adrenalined** [comment]
Just realized now that I posted a bad screen shot, that was for something else.  I've updated the link here to illustrate.

[Here is the updated one](https://imgur.com/a/YDIExAl)

**Comment by p3lim** [comment]
Kind of intentional, I just manually mark it as new when I add it then a (undefined) time later I just remove it.

It would be nice to be able to automatically hide it when the user has in some form "visited" the option, but that's a low priority.

**Comment by Adrenalined** [comment]
Ahh ok, makes sense.  I appreciate the insight.

**Comment by p3lim** [comment]
Was actually easier than I thought

**Comment by Adrenalined** [comment]
Oh, awesome!
